#pragma once

// Matrix
#define MATRIX_ROWS 10 
#define MATRIX_COLS 7
#define MATRIX_ROW_PINS { GP9, GP10, GP11, GP12, GP13 }
#define MATRIX_COL_PINS { GP2, GP3, GP4, GP5, GP6, GP7, GP8 }
#define DIODE_DIRECTION ROW2COL

// Transport
#define MASTER_LEFT
#define SERIAL_USART_FULL_DUPLEX
#define SERIAL_USART_TX_PIN GP0
#define SERIAL_USART_RX_PIN GP1
#define SERIAL_USART_DRIVER SIO0


// Keyboard
#define TAPPING_TERM 250
#define ONESHOT_TIMEOUT 250
#define ONESHOT_TAP_TOGGLE 0
#define HOLD_ON_OTHER_KEY_PRESS
#define QUICK_TAP_TERM 0

// Other
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET