# Required
BOOTLOADER = rp2040
MCU = RP2040
BOARD = GENERIC_RP_RP2040
SPLIT_KEYBOARD = yes
SERIAL_DRIVER = vendor 

# Features
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
EXTRAKEY_ENABLE = yes
NKRO_ENABLE = yes


# Copy
OLED_ENABLE = no
ENCODER_ENABLE = no
CONSOLE_ENABLE = no
EXTRAKEY_ENABLE = yes
TAP_DANCE_ENABLE = yes
MOUSEKEY_ENABLE = no