# Features
EXTRAKEY_ENABLE = yes
NKRO_ENABLE = yes
BOOTMAGIC_ENABLE = yes

TAP_DANCE_ENABLE = no
MAGIC_ENABLE = no
MOUSEKEY_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
COMBO_ENABLE = no
AUDIO_ENABLE = no
KEY_OVERRIDE_ENABLE = no
RGBLIGHT_ENABLE = no
LEADER_ENABLE = no
MIDI_ENABLE = no
UNICODE_ENABLE = no
BLUETOOTH_ENABLE = no
DYNAMIC_TAPPING_TERM_ENABLE = no
BACKLIGHT_ENABLE = no
OLED_ENABLE = no
ENCODER_ENABLE = no
